name: Moras CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    type: ["checks_requested"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Rust nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - name: JS/JSON format check
        working-directory: ./src-ui
        run: |
            npm install
            npm run format-check

      - name: Rust format check
        working-directory: ./src-tauri
        run: cargo fmt -- --check

      - name: Tauri dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev libwebkit2gtk-4.0-dev webkit2gtk-driver xvfb protobuf-compiler

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo test
        working-directory: ./src-tauri
        run: cargo test
        env:
          RUSTFLAGS: "--cfg ci"

      #- name: Cargo build
        #working-directory: ./src-tauri
        #run: cargo build --release

      - name: Build Rust doc
        if: github.ref == 'refs/heads/main'
        working-directory: ./src-tauri
        run: |
          cargo doc --no-deps

      - name: Generate Report
        if: github.ref == 'refs/heads/main'
        working-directory: ./src-tauri
        run: |
          ../scripts/reoport.sh
          mv *.html target/doc/report.html

      - name: Deploy Doc
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src-tauri/target/doc

