name: Moras CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Format check
        working-directory: ./src-tauri
        run: cargo fmt -- --check

      - name: Format check
        working-directory: ./src-tauri
        run: cargo fmt -- --check

      - name: Tauri dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev libwebkit2gtk-4.0-dev webkit2gtk-driver xvfb

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo test
        working-directory: ./src-tauri
        run: cargo test

      - name: Cargo build
        working-directory: ./src-tauri
        run: cargo build --release

